name: restroapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CF./gradlew assembleDebugBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^0.4.0+17
  device_info: ^0.4.2+1
  connectivity: ^0.4.2
  progress_dialog: ^1.2.2
  http: ^0.12.0+3
  fluttertoast: ^4.0.1
  shared_preferences: ^0.5.0
  path_provider: ^1.6.5
  sqflite: ^1.3.0
  carousel_slider: ^2.2.1
  font_awesome_flutter: ^8.4.0
  geocoder: ^0.2.1
  geolocator: ^4.0.3
  google_maps_flutter: ^0.5.12
  flutter_html: ^0.11.1
  flutter_share: 1.0.2+1
  url_launcher: ^5.4.2
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^0.8.4
  razorpay_flutter: ^1.1.3
  firebase_crashlytics: ^0.1.3+3
  carousel_pro: ^1.0.0
  #flutter_web_view: ^0.0.6
  firebase_analytics: ^5.0.11
  event_bus: ^1.1.0
  intl: ^0.16.1
  flutter_tags: "^0.4.8+1"
  badges: ^1.1.1
  cached_network_image: ^2.2.0+1
  maps_launcher: ^1.2.0
  flutter_pull_to_refresh: ^1.0.0
  dio: ^3.0.9  #latest version
#  webview_flutter: ^1.0.3
  webview_flutter: ^0.3.22+1
  keyboard_visibility: ^0.5.6
#  flutter_inappwebview: ^4.0.0+4
  flutter_open_whatsapp: ^0.1.2
  flutter_rating_bar: ^3.0.1+1
  image_picker: ^0.6.7+11
  compressimage: ^0.1.1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/gift.png
    - images/about.png
    - images/about_image.png
    - images/home.png
    - images/deliveryaddress.png
    - images/my_order.png
    - images/myfav.png
    - images/myprofile.png
    - images/refer.png
    - images/booknow.png
    - images/arrow_right.png
    - images/sign_in.png
    - images/sign_out.png
    - images/hamburger.png
    - images/home_basket.png
    - images/home_contact.png
    - images/home_offers.png
    - images/home_order.png
    - images/home_history.png
    - images/home_categories.png
    - images/shadow.png
    - images/home_order.png
    - images/pickup.png
    - images/deliver.png
    - images/dining.png
    - images/splash.jpg
    - images/icon_home_categories.png
    - images/image_pickup.png
    - images/deliver.png
    - assets/app_config.json
    - images/rightArrow.png
    - images/close.png
    - images/topArrow.png
    - images/cancelpopupicon.png
    - images/carticon.png
    - images/contacticon.png
    - images/historyicon.png
    - images/searchcion.png
    - images/backgroundimg.png
    - images/loyality.png
    - images/process_img.png
    - images/bottom_bg.png
    - images/groceryicon.png
    - images/restauranticon.png
    - images/cancel_cart.png
    - images/next_arrow_icon.png
    - images/cancel_icon.png
    - images/login_img.jpg
    - images/login_restro_bg.jpg
    - images/empty_cart.png
    - images/gifticon.png
    - images/whatsapp.png
    - images/placeHolder.png
    - images/walleticon.png
    - images/cashbackicon.png
    - images/orderrefund.png
    - images/emptywalletbalancegreaphics.png
    - images/walletbalancegreaphics.png
    - images/fbicon.png
    - images/linkedinicon.png
    - images/twittericon.png
    - images/whatsappicon.png
    - images/youtubeicon.png
    - images/instagram.png
    - images/fblogin_btn.png
    - images/google_logo.png
    - images/f_logo_white.png
    - assets/en.json
    - assets/malay.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages